/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function ModelInjeksi({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./animastiinjection01.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log(actions)
    actions.liquid.play(0)
    actions.Mesh_13Action.play(1)
    actions.Mesh_5Action.play(2)
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Node_0" position={[-0.68, -0.15, 0.07]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="02-_FIX_PLATEN-1" position={[0.16, 0, 0.13]} rotation={[0, -1.55, -1.57]}>
            <group name="Body_1">
              <group name="3DGeom-159">
                <group name="Node_6">
                  <mesh
                    name="Mesh_0"
                    geometry={nodes.Mesh_0.geometry}
                    material={materials.texture}
                  />
                </group>
              </group>
              <group name="3DGeom-160">
                <group name="Node_9">
                  <mesh
                    name="Mesh_1"
                    geometry={nodes.Mesh_1.geometry}
                    material={materials.Thread}
                  />
                </group>
              </group>
            </group>
            <group name="Body_2">
              <group name="Node_12">
                <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.Mtl} />
              </group>
            </group>
            <group name="Body_3">
              <group name="Node_15">
                <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials.Mtl} />
              </group>
            </group>
          </group>
          <group
            name="03-_MOVE_PLATEN-2"
            position={[-0.36, 0, 0.14]}
            rotation={[-Math.PI, 1.55, -1.57]}
          >
            <group name="Body_1001">
              <group name="3DGeom-301">
                <group name="Node_20" />
              </group>
              <group name="3DGeom-302">
                <group name="Node_23">
                  <mesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={materials.Mtl2} />
                </group>
              </group>
            </group>
          </group>
          <group name="06_-_NOZLE-1" position={[-0.14, 0, 0.14]} rotation={[0, -1.55, -1.57]}>
            <group name="Body_1002">
              <group name="Node_37">
                <mesh name="Mesh_9" geometry={nodes.Mesh_9.geometry} material={materials.Mtl4} />
              </group>
            </group>
            <group name="Body_2001">
              <group name="Node_40">
                <mesh name="Mesh_10" geometry={nodes.Mesh_10.geometry} material={materials.Mtl4} />
              </group>
            </group>
            <group name="Body_3001">
              <group name="3DGeom-465">
                <group name="Node_28">
                  <mesh name="Mesh_6" geometry={nodes.Mesh_6.geometry} material={materials.Mtl6} />
                </group>
              </group>
              <group name="3DGeom-466">
                <group name="Node_31">
                  <mesh name="Mesh_7" geometry={nodes.Mesh_7.geometry} material={materials.Mtl5} />
                </group>
              </group>
              <group name="3DGeom-467">
                <group name="Node_34">
                  <mesh name="Mesh_8" geometry={nodes.Mesh_8.geometry} material={materials.Mtl4} />
                </group>
              </group>
            </group>
          </group>
          <group
            name="07-_BASE_NOZZLE-1"
            position={[2.04, 0, -0.22]}
            rotation={[-Math.PI, 1.55, -1.57]}
          >
            <group name="Body_1003">
              <group name="Node_44">
                <mesh name="Mesh_11" geometry={nodes.Mesh_11.geometry} material={materials.Mtl7} />
              </group>
            </group>
          </group>
          <group name="13_-_SCREW-1" position={[1.51, 0, 0.11]} rotation={[-Math.PI / 2, 0, -3.13]}>
            <group name="Body_1004">
              <group name="Node_48">
                <mesh
                  name="Mesh_12"
                  geometry={nodes.Mesh_12.geometry}
                  material={materials.Mtl9}
                  scale={[1, 0.76, 1]}
                />
              </group>
            </group>
          </group>
          <group name="14_-_NOZZLE_SPRUE-1" position={[0.1, 0, 0.13]} rotation={[0, -1.55, -1.57]}>
            <group name="Body_1007">
              <group name="Node_60">
                <mesh name="Mesh_15" geometry={nodes.Mesh_15.geometry} material={materials.Mtl10} />
              </group>
            </group>
          </group>
          <group name="Camera-1" position={[0.62, -9.03, 0.12]} rotation={[Math.PI / 2, 0, 0]} />
          <group
            name="CAVITY_PLATE-1"
            position={[-0.09, 0, 0.25]}
            rotation={[-Math.PI / 2, 0, 1.59]}
          >
            <group name="Body_1005">
              <group name="Node_52">
                <mesh name="Mesh_13" geometry={nodes.Mesh_13.geometry} material={materials.Mtla} />
              </group>
            </group>
          </group>
          <group name="CORE_PLATE-1" position={[-0.02, 0, 0.14]} rotation={[Math.PI / 2, 0, 1.55]}>
            <group name="Body_1006">
              <group name="Node_56">
                <mesh name="Mesh_14" geometry={nodes.Mesh_14.geometry} material={materials.Mtlb} />
              </group>
            </group>
          </group>
        </group>
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.001']}
          position={[0.6, 0.32, 0.07]}
          scale={[0.19, 0.04, 0.19]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/animastiinjection01.glb')
